### PR TITLE
Fix 0.1: GioiThieuVeNgonNguLapTrinh

### PR DESCRIPTION
**Pull request by xuancanh**
Fixed minor spelling errors, reorganized and reformatted documents

### CODE REVIEW

**Comment by trandatnh** [comment]
LGTM

@nguyenchiemminhvu can you check?

**Comment by thangngoc89** [comment]
@trandatnh Please squash before merging. Github can do it.

**Comment by xuancanh** [comment]
@thangngoc89 Im using github web version so I'm not so sure about how can I do that :cry:

**Comment by thangngoc89** [comment]
@xuancanh yup. Just skip that for now.

@trandatnh just check for content right now since we do have issue with current markdown

**Comment by trandatnh** [comment]
@thangngoc89 OK

**Pull request merged**
